# InSpec test for recipe ssh_authorized_keys_test::resource

# The InSpec reference, with examples and extensive documentation, can be
# found at https://www.inspec.io/docs/reference/resources/

describe file('/home/bob/.ssh') do
  it { should be_directory }
  it { should be_owned_by 'bob' }
  it { should be_grouped_into 'bob' }
  its('mode') { should cmp '0700' }
end

bob_content = [
  '# Generated by Chef',
  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCctNyRouVDhzjiP+u3R2+C0nD4VgsRgN9rOiz'\
  'D2ePBrf8508VR5envsmEY5oF+TM3k/wb2xBY45KXOu9yQjQi9RcCYvrCAu3wPTrx07vRetkDIvs'\
  '/O383zQQanrHMGckNzh83uwDU4JcJqBP2EwkTMUqlk6xyrGuQyjmWFKWjjUUkmHFII5azAh+9bp'\
  '4OjULE9h9fy4Y3ZOxHMrHuC5AjkWhvy88ItmGBf0sj0iW0893UVrzdfB20dz+G9pM2lE5NK/b/z'\
  'fF7UlIjgI9oR9w2+YaNZE/fmuHpH94Gx/Ptlwxb2tmdEReA8DPsnHMIML3ltcpJrwgVdTJEAAz1'\
  'JnARx bob@acme.com',
  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCySLKbpFRGCrKU/N6jNVB8vZLzexKbkq2bXPR'\
  'KUakmf8qrSQI9Bl1C8+6//uKpe909DrZzEkJzPC9BgpNnWtJ25SxHogKb1SybAk0OFc61X7wl1k'\
  'noo+OcuW6Moi0vpNiUGy2VnM0nyecLoQxggvnj1392uoMdS4VY71PGdcBac7p9IwAwYxlsuFEKR'\
  'cfKisJAHDEblgSFyC9lLMMjTSxxKn8s5AaR1h+Lb3Kwibd7ikvIgYRybTbD12FtQRxuWZBVm39C'\
  'M3539gT6514IaYyYVDyIEFDyGjK2UV27ah56jMaRFGX4IIh2gH5P2XaV7As5p8RPYoWwf+pCz19'\
  'mrPd/ bob@home.com comment',
].join("\n") << "\n"

describe file('/home/bob/.ssh/authorized_keys') do
  it { should be_file }
  it { should be_owned_by 'bob' }
  it { should be_grouped_into 'bob' }
  its('mode') { should cmp '0600' }
  its('content') { should match bob_content }
end

describe file('/home/bob2/.ssh') do
  it { should be_directory }
  it { should be_owned_by 'bob2' }
  it { should be_grouped_into 'bob2' }
  its('mode') { should cmp '0700' }
end

describe file('/home/bob2/.ssh/authorized_keys') do
  it { should be_file }
  it { should be_owned_by 'bob2' }
  it { should be_grouped_into 'bob2' }
  its('mode') { should cmp '0600' }
  its('content') { should match bob_content }
end

describe file('/home/alice/.ssh') do
  it { should be_directory }
  it { should be_owned_by 'alice' }
  it { should be_grouped_into 'alice' }
  its('mode') { should cmp '0700' }
end

alice_content = [
  '# Generated by Chef',
  'no-port-forwarding,no-agent-forwarding,no-X11-forwarding,'\
  'command="echo \'Please login as the user \"bob\" rather than the user '\
  '\"alice\".\';echo;sleep 10" '\
  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCySLKbpFRGCrKU/N6jNVB8vZLzexKbkq2bXPR'\
  'KUakmf8qrSQI9Bl1C8+6//uKpe909DrZzEkJzPC9BgpNnWtJ25SxHogKb1SybAk0OFc61X7wl1k'\
  'noo+OcuW6Moi0vpNiUGy2VnM0nyecLoQxggvnj1392uoMdS4VY71PGdcBac7p9IwAwYxlsuFEKR'\
  'cfKisJAHDEblgSFyC9lLMMjTSxxKn8s5AaR1h+Lb3Kwibd7ikvIgYRybTbD12FtQRxuWZBVm39C'\
  'M3539gT6514IaYyYVDyIEFDyGjK2UV27ah56jMaRFGX4IIh2gH5P2XaV7As5p8RPYoWwf+pCz19'\
  'mrPd/ alice@acme.com',
].join("\n") << "\n"

describe file('/home/alice/.ssh/authorized_keys') do
  it { should be_file }
  it { should be_owned_by 'alice' }
  it { should be_grouped_into 'alice' }
  its('mode') { should cmp '0600' }
  its('content') { should match alice_content }
end
